### ISSUE TITLE
[removed due to vandalism]

### ISSUE THREAD

**Issue by cerealwithmilk** [cereaIwmilk/VegaX#1]
[removed due to vandalism]

**Comment by cereaIwithlmilk** [comment]
Hi Santagio! I am not "Impersonating" you! it just happens to be that we both have the same pfp and name! And this is infact legit. Test it yourself on a vm if you dont believe me, Also i think the part where you insult me for being Trans is very Homophobic! Please dont write false claims under this rep if you are uneducated, if you would like send me you're discord so we can resolve this issue! Thanks you for your time -amian
